# Generated by Django 4.2 on 2023-12-16 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=100)),
                ('client_second_name', models.CharField(max_length=100)),
                ('client_phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_first_name', models.CharField(max_length=50)),
                ('master_second_name', models.CharField(max_length=50)),
                ('master_phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150)),
                ('service_description', models.TextField(max_length=500)),
                ('service_cost', models.PositiveIntegerField()),
                ('service_duration', models.PositiveIntegerField()),
                ('client', models.ManyToManyField(to='main_temp.clients')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='main_temp.master')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_temp.clients')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_temp.services')),
            ],
        ),
    ]
